#!/bin/sh

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Neovim config is different than regular vim
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s ~/.vim ${XDG_CONFIG_HOME}/nvim
ln -s ~/.vimrc ~/.vim/init.vim

if ! type "pip3" > /dev/null; then
  pip3 install neovim
fi

if ! type "pip" > /dev/null; then
  pip install neovim
fi

