#!/bin/sh

git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew

~/.brew

# ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

# Neovim setup
~/installs/vim
